# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Ĝi estas Blogo
baseurl:          "/flash_cc2531"
auxtoro: Jean Michault

exclude: [ _locale , _scripts , "*.backup", "*.bak" ]

plugins:
  - jekyll-relative-links
  - jekyll-sitemap

relative_links:
  enabled:     true
  collections: true
